version: '3.8'
services:
    frontend:

    backend:

    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ToDoItems
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
networks:
    my-custom-network:
        driver: bridge