version: '3.8'
services:
    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        depends_on:
            - backend
        networks:
            - my-custom-network
    backend:
        build: ./backend/todoApi
        ports:
            - "5000:5000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Host=database;Database=ToDoItems;Username=postgres;Password=postgres
        depends_on:
            - database
        networks:
            - my-custom-network
    database:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ToDoItems
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
networks:
    my-custom-network:
        driver: bridge